# Generated by Django 4.2.16 on 2024-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
            ],
        ),
    ]
